<?php

/**
 * @file
 * Contains newsletterapi.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function newsletterapi_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the newsletterapi module.
    case 'help.page.newsletterapi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Newsletter form with fields to send to api.') . '</p>';
      return $output;

    default:
  }
}
